name: build-deploy-extension
on: workflow_dispatch
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: install @vscode/vsce
        run: npm install -g @vscode/vsce
      - name: create package .vsix file
        run: vsce package
      - name: save build file
        uses: actions/upload-artifact@v4
        with:
          name: .vsix file
          path: |
            build